apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: nodejs-mini
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-mini
  labels: 
    app: nodejs-mini
spec: 
  containers: 
  - name: nodejs-mini
    image: spwilson87/nodejs-mini
    ports:
    - containerPort: 5000